# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class {{ .FormulaName }} < Formula
  desc "{{ .Description }}"
  homepage "https://toss.im"
  version "{{ .Version }}"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/toss/apps-in-toss-ax/release/download/v{{ .Version }}/ax_darwin_arm64.tar.gz"
      sha256 "{{ .Checksum.ax_darwin_arm64 }}"

      def install
        bin.install "ax"
        (bash_completion/"ax").write `#{bin}/ax completion bash`
        (fish_completion/"ax.fish").write `#{bin}/ax completion fish`
        (zsh_completion/"_ax").write `#{bin}/ax completion zsh`
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/toss/apps-in-toss-ax/release/download/v{{ .Version }}/ax_darwin_amd64.tar.gz"
      sha256 "{{ .Checksum.ax_darwin_amd64 }}"

      def install
        bin.install "ax"
        (bash_completion/"ax").write `#{bin}/ax completion bash`
        (fish_completion/"ax.fish").write `#{bin}/ax completion fish`
        (zsh_completion/"_ax").write `#{bin}/ax completion zsh`
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/toss/apps-in-toss-ax/release/download/v{{ .Version }}/ax_linux_arm64.tar.gz"
      sha256 "{{ .Checksum.ax_linux_arm64 }}"

      def install
        bin.install "ax"
        (bash_completion/"ax").write `#{bin}/ax completion bash`
        (fish_completion/"ax.fish").write `#{bin}/ax completion fish`
        (zsh_completion/"_ax").write `#{bin}/ax completion zsh`
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/toss/apps-in-toss-ax/release/download/v{{ .Version }}/ax_linux_amd64.tar.gz"
      sha256 "{{ .Checksum.ax_linux_amd64 }}"

      def install
        bin.install "ax"
        (bash_completion/"ax").write `#{bin}/ax completion bash`
        (fish_completion/"ax.fish").write `#{bin}/ax completion fish`
        (zsh_completion/"_ax").write `#{bin}/ax completion zsh`
      end
    end
  end
end